
import React from 'react';
import { 
  AlertTriangle, 
  CheckCircle2, 
  ShieldAlert, 
  ArrowRight,
  Info,
  ExternalLink
} from 'lucide-react';
import { AnalysisResult } from '../types';
import { PieChart, Pie, Cell, ResponsiveContainer } from 'recharts';

interface AnalysisResultDisplayProps {
  result: AnalysisResult;
}

const AnalysisResultDisplay: React.FC<AnalysisResultDisplayProps> = ({ result }) => {
  const getLevelColor = () => {
    switch (result.threatLevel) {
      case 'Low': return 'text-green-400 border-green-500/20 bg-green-500/5';
      case 'Medium': return 'text-amber-400 border-amber-500/20 bg-amber-500/5';
      case 'High': return 'text-orange-400 border-orange-500/20 bg-orange-500/5';
      case 'Critical': return 'text-red-400 border-red-500/20 bg-red-500/5';
      default: return 'text-slate-400';
    }
  };

  const getLevelIcon = () => {
    if (result.riskScore < 30) return <CheckCircle2 className="text-green-500" size={24} />;
    if (result.riskScore < 70) return <AlertTriangle className="text-amber-500" size={24} />;
    return <ShieldAlert className="text-red-500" size={24} />;
  };

  const chartData = [
    { value: result.riskScore },
    { value: 100 - result.riskScore }
  ];

  const COLORS = [
    result.riskScore > 75 ? '#ef4444' : result.riskScore > 40 ? '#f59e0b' : '#22c55e',
    '#1e293b'
  ];

  return (
    <div className="mt-8 space-y-6 animate-in fade-in slide-in-from-top-4 duration-500">
      {/* Top Banner */}
      <div className={`p-6 rounded-2xl border ${getLevelColor()} flex flex-col md:flex-row items-center gap-6 shadow-xl`}>
        <div className="h-32 w-32 relative shrink-0">
          <ResponsiveContainer width="100%" height="100%">
            <PieChart>
              <Pie
                data={chartData}
                innerRadius={35}
                outerRadius={50}
                paddingAngle={0}
                dataKey="value"
                startAngle={90}
                endAngle={450}
              >
                {chartData.map((entry, index) => (
                  <Cell key={`cell-${index}`} fill={COLORS[index % COLORS.length]} stroke="none" />
                ))}
              </Pie>
            </PieChart>
          </ResponsiveContainer>
          <div className="absolute inset-0 flex flex-col items-center justify-center">
            <span className="text-2xl font-bold">{result.riskScore}</span>
            <span className="text-[10px] font-bold opacity-60">RISK</span>
          </div>
        </div>

        <div className="flex-1 text-center md:text-left">
          <div className="flex items-center justify-center md:justify-start gap-2 mb-2">
            {getLevelIcon()}
            <h3 className="text-2xl font-bold uppercase tracking-tight">{result.threatLevel} Threat Level</h3>
          </div>
          <p className="text-slate-300 leading-relaxed text-sm lg:text-base">
            {result.summary}
          </p>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {/* Red Flags */}
        <div className="p-6 bg-slate-900 border border-slate-800 rounded-2xl">
          <div className="flex items-center gap-2 mb-4 text-rose-400 font-bold uppercase text-xs tracking-widest">
            <AlertTriangle size={16} />
            Detected Indicators
          </div>
          <ul className="space-y-3">
            {result.indicators.map((indicator, idx) => (
              <li key={idx} className="flex gap-3 text-sm text-slate-300">
                <div className="shrink-0 w-5 h-5 bg-rose-500/10 rounded flex items-center justify-center text-rose-400">
                  <span className="text-[10px] font-bold">{idx + 1}</span>
                </div>
                {indicator}
              </li>
            ))}
          </ul>
        </div>

        {/* Action Plan */}
        <div className="p-6 bg-slate-900 border border-slate-800 rounded-2xl">
          <div className="flex items-center gap-2 mb-4 text-emerald-400 font-bold uppercase text-xs tracking-widest">
            <ShieldAlert size={16} />
            Recommended Actions
          </div>
          <ul className="space-y-3">
            {result.recommendations.map((rec, idx) => (
              <li key={idx} className="flex gap-3 text-sm text-slate-300">
                <ArrowRight size={16} className="shrink-0 text-emerald-500 mt-0.5" />
                {rec}
              </li>
            ))}
          </ul>
        </div>
      </div>

      <div className="p-4 bg-indigo-500/5 border border-indigo-500/20 rounded-xl flex items-start gap-3">
        <Info className="text-indigo-400 shrink-0 mt-0.5" size={18} />
        <p className="text-xs text-indigo-300/80 leading-relaxed">
          PhishGuard analysis is generated by an advanced AI model. While highly accurate at identifying common patterns, 
          always exercise your own judgment before interacting with suspicious content.
        </p>
      </div>
    </div>
  );
};

export default AnalysisResultDisplay;
